jobs:
  include:
  - stage: Build

    sudo: required
    language: minimal
    services:
    - docker
    script: docker build --build-arg "APP_VERSION=$(make version)" -t "${DOCKER_USER}/talks:$(make version)" .
    after_success:
    - echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
    - docker push "${DOCKER_USER}/talks:$(make version)"

  - stage: Publish

    sudo: required
    language: minimal
    services:
    - docker
    script:
    - echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
    - curl -q -sSL --max-time 10 "https://raw.githubusercontent.com/ViBiOh/scripts/master/bootstrap" | bash -s "docker_promote"
    - scripts/docker_promote "${DOCKER_USER}/talks" "$(make version)"

  - stage: Index

    language: go
    go: 1.13
    env:
    - GO111MODULE=on
    script:
    - make
    - ./script/index

  - stage: Deploy

    language: minimal
    script: |
      sed \
        -e "s|\${ALGOLIA_APP}|${ALGOLIA_APP}|g" \
        -e "s|\${ALGOLIA_KEY}|${ALGOLIA_READ_ONLY_KEY}|g" \
        -e "s|\${ALGOLIA_INDEX}|${ALGOLIA_INDEX}|g" \
        -e "s|\\\$|\$\$|g" \
        docker-compose.yml > docker-compose-env.yml
      curl -q -sSL --max-time 10 "https://raw.githubusercontent.com/ViBiOh/scripts/master/bootstrap" | bash -s "deploy"
      scripts/deploy talks "@docker-compose-env.yml"

stages:
  - Build
  - name: Publish
    if: branch = master && type = push
  - name: Index
    if: branch = master && type = push
  - name: Deploy
    if: branch = master && type = push

notifications:
  email: false
