apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: talks-algolia
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: job
      version: '0.0.8'
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: talks-algolia
    image:
      name: vibioh/talks
      tag: '202201300755' # {"$imagepolicy": "default:flux-talks-web:tag"}
    command:
      - /revealgolia
      - -source
      - /www/doc/
      - -prefixFromFolder
    config:
      REVEALGOLIA_LOGGER_JSON: true
    secrets:
      REVEALGOLIA_APP: AgBRxq9shwHT+qvivvK/dQsopJLsIFzhKSoGUYTrNGxO4QskJPctTuQWfE9msM44NaA1KmcprqJljnW8GoeWWjo3+t4lKsCckENVKwC0b+uIpJeiLNXDYCuqa83j5nfZYcGCax4qf7GLdGsoIBhe++f5FFDksP2WXwarbIunf8T4ndRKtF7oadXNgykPK9ituPK1Bx/94SQ5oQNWgzz2WK+DcMAMBb2eZhbTI81xZO0eUNkBdAly04D/tZVoQSL5sKh7OVRxp6bEpGe3+Ypbd2Hp224PS5u6lpyGCzVfrEfKK1Kd+encvIQhqLjP/pXOGUI5x6gGcHnRah08mW2j46QtXieKQD222luAu3/ff/mdICyf/D55/McCaLlB4Wxe7Jp6uvrRBAGhf4P6wOB+H7W2jGl0fjPaKtgsuY/T0zpFlWtdcI7yCoB8V0EY6rXVlQBh9LNGp5YtxYxzCqqxH8zrjTKoi1kRm0U3mKYlAbJ27Fr93dSggflKHIacM7TvRmqAmYGc4Rq5cbFjDIxQcwsK2qYOquOF/nJchlAHTFpWy1OXt58brBlqEDqN0UDanOVnE9ZJMM0sJCBpuyJU4Jr4N48YwOt+/0/oxBp/5r3DQjX01CZOpwhNTFNRjWkqkPey6G7ErbFYg8CmJinbzjFmdWc0UAyV14kX5HkVf21hmi6tA4IuxNf1LlSTMvBT9thKi3AcqJCuLSTj
      REVEALGOLIA_INDEX: AgCBoLqcnXJijrE3WuwL8B5x0A4OjO67TfFJw7FZNRAsBIzV87aS14SGuSPMtbX/o27t7emPF5adTuQKzAVQqSkLxR6Nrfg1Uk78rxP5TAAI0H+GWGQiAjU5siSC+P97Ny6zrPZ2rpzr5gf7+mWWxkPwnrPK792LjWzghPrYAseuXeiVqgfDldbS1iujjGh1ZFxS6J7LSahsqGpxfBMmyUSq+n9hi/TXIKIddds7eFfZVoM616gacWyc4ovI331/gj1UmdgeTpi31kiHTkLzyiv7RiRhekv7qM6OpPGScwknbtPfCOnpzo4t7mnLy6yyAaWFfkt+lEOFBfFX/H1YzitZejQggyUFAY9RM/An+jaryBMUWjLhOsSNdmhim4ezMWJCbxxM0RUZwQ810q4Oe4HPpIwih34Zqqc+kFh828pOW4MNAUa+eaMS+l6fh//mX9kQ5IIGGqxGp90MXSauE3VZPHTZx7Xwg19v5WQGiEpFNBbp6iqGRBShGk9eQM+vYKh6cx2eskOfs8ExNPn/T8kuMK1nuPTz6GaJe8dfpcTlp5nz4tneRzxAe0Ik50MB42mqbQGvVVPWRweda2S4aT+hC1F9mxfoNze50odwpaNGtNyBa9OWKv7Q3guBgfSS/bhh0rASciLI8vu4Utc2y5NDMS2eYvWmgHrDgdHcQE+crGLxs0idZtFK4ce0mOwa6h7UNKI3ug==
      REVEALGOLIA_KEY: AgDVwdEIs4Qi4nl8fWcgUtw2zR20OXr1bKa81ch7X5AqKB9ow+kNtgbqtJfrlfUDrqrZ/fGMC8jQiFS4hqeliKcvotLo3AHukzaFaR1u+NsUSWU9Q9eAmEbE7C4Gy1hG5z2rAwJHNoT7SgJ3R+psZdfuRogUbbwepAbaReW2yag+S7JaU8akIdzhPZCsfHYdr62QWofDGbirgAtgsF9/TPPMd4wNtDbJSjxpJFHFH3AVu88q6klv1/VtlMEGteoUJozEmoQXAqjPRDPtv5jGGNX9hp8V0K9Yz32UdRN4O9gpYtoAdI84r7c2MkYNEnj+274Ucahp0zFi1e5mVwBaiVd42ljxlQLTBsNjRErC5+dpg4D/RMOE8oYkhaAWEKFKjFvYyqHHSIt3m/BuEdwOh5AR+qR/TGp/EHxCiuSCn6DGE1XG132VD6+7spraopbt88uLjdcHoN8+tXJtl7wmuvcS061thoqFtm3RsgrkMmeT1qZ+DQTWPiWcm0DBNc6hLIyAO98w94Mj8rdC3tMwUGRVbxryOieB9m1Fj8Pi4hbrO3Bm2jARL4v/ntfaSKt92qs3EmYGv6G9Eph2GTOjToqe6V1c+iGjj4w5P3rU1n3rd4rldBDf+ATxUz7OMO6K1kvZ2SqUWzbG9wlY0BoQ8Z1Ex9l4Cj47zw9LEixKpgJHiZsxyd+Uo7KTKNAwWYKWZnCCgQ+vuM10WecetcxSlArYt86ZrejB/6OXGAMixKXxmw==
