apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: talks-algolia
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: job
      version: '0.0.7'
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: talks-algolia
    image:
      name: vibioh/talks
      tag: '202111140925' # {"$imagepolicy": "default:flux-talks-web:tag"}
    command:
      - /revealgolia
      - -source
      - /www/doc/
      - -prefixFromFolder
    config:
      REVEALGOLIA_LOGGER_JSON: true
    secrets:
      REVEALGOLIA_APP: AgBSP162AuGJQoyGQzveqPU1q5AsBG7iv8QwxS5idGuhpOI9Qtyy7ZaTSdAi4TjkLtZ5tW0gNQ5v3zv3kxpks6IAuKnoOV8UHk08bXOSlaPtELUDXERrDd+CXVYP5AptMn/plXtLW2imwk+WFLdCuZnxgUJCbURyvywyKZxmZaAmY2B9bcu2B1IAOxZiV6z9TiKfsm2t6OUTJ9mK0Ke2Cq3zvMfRxIUuFGg62oJH+ugJTDIKY3yfg1DviOhm2PLTWOY6IFcvoKMSSL66bZ+Z/Xpe5Ket664/OhuyWy4k0kS5uKYj94+/718/EzUq+zd6Kk89iNUxuMseSwRs4bugVkSaTuSpz7wSN/Vu1JMguW40jtrQnaQc+M+AcqlAWRJmcOpeHdUkuAV9JTf8EUtbG9+GidZAnbHQBT1me+CkL2JFsKfeclkak2NEyea6qDt1EU1vI7Ddsz7gfoUJc0rxe0VoXQD1T4lYjOVpqNM7BNO13M0czh5ZJqsGsGyoF9EoDPu2kmqhbmwdY8IC26QOeeF9S05Sj0kKAtc+6/e5mKRzb3u7U8XCrkpfqUiU2cAxBdpfe/LDfL+xlFRNbl5qDCELnbfACW9EPaVrGhGvCXj7708gFO/ZvTVSjvReUif1125+JkJRNcU3rLm+/NeC9gGLuW+70a8p5ijEFnF/t3sj/QTOubLX2Y0+/TnMtBZq2cNs+RP4oq7zf4hM
      REVEALGOLIA_INDEX: AgCYhtet2FyYKVM9XpCiKAuQMtX48vGdPgQJVvryGqtCf3f2r7PaJP+rajyHYW0e56V8iPCc5zQAp+WTbBZsKpr8I2XDLkk99xS6+boiW5VWPREKTfx/j8QYPLsx6LpjmJT/BmkQFlwA8/iwvoxwow5DHkobGGAckivFafPoCRZAzy5x23dwZzaHQjb9ovon2J1qN1Uo+DTdp/qHH1kHR7dWLAVwQAJCkTDVjor9R512mjLYszzlUhxE9eqtR3RtJWXYPZ9X87fzxtLf8K1XYZvWZaz10XbICaqxQH9Q7zplfHn5GTQgh4JvT4LXrTQoCBZ2FfCwjXJ7TxfaCuO+dofJMxpMyaMnIQSeYaIhm0OE/i+EaFkDu91E1qUCxsyob6ZBLwMKPzQq/6KiO46EthJCAj5UGZ4xSUGQ5FFqCDbIp6DW65oi/bw11QWtL5QlBzu/1Wjye/haRYxLguSs2aKTZrUodTaN3kwx6mRqkEFRX3qgQgeZb7U7XIqeRzbJGNyPZ2t86um1DQJ1p+02QYWxq0HljGQBEIe2ukQDLBIo/a52U1SoFsMfAXypkCGotwpg8tLl1uYa0MPPxsJTjmnnWsIYBWVnEKTKEXPpBzDmBQz6oZLfe6MIUGAnL9ZOlQTIRjSdtjK1TIcPhgcR8my8UjFs1VAorATvFJnzOTRtSoc1ApeLU+Nqq/EP+3B7wggowwKXMw==
      REVEALGOLIA_KEY: AgAkJ0q8cN7LrMSBcFh5G0sp6rWOf5KsYAVasHRPkM8swReRwYqjgQqGxtsdiqEOlAGMa0iDL3sdYAGGx2ZKNby69sJMIFsvaHO+wGsESMPenYscs1RvFiy7cfWHoV1aNUIln8d3YQMYdC9kKB1GUoI3SvvEeAlrO2h0HxdMVAJSmvKol2jZ4yo0EDtXMZxppXo41IRG4kRVtPz7DqlJBhorhb37RIVaHc+BYBibV1L0/HPBamXMJ6Xr8O5EdLswS8yFnvSF1wmL5ihQgJGwk4ooWLg7+xaguI2XEcuDutGTaWGLgsCqMUBZeXe/Q7TVVLDjZCWpJ0enAOK4yKuujAuaUXYulnSWS5j4jqmwcXfITw+w8YT3wfI+A1a/0drBxH+a8xxLzQT1BuW5HhHW9QMkNPIoIWoUGfrmadFAUqOBhbmuzzniB31051v8Sv1fOv82GbIl4ygHT1In92BotHlhF6dt0dyLUqiVqAS1vMAZUDzCLgXx3o9znNKzS8JRc8yIt/NVDRsYTHcNEcFzhGJ4cluuULHFFcaIVPQwej3iEJL8Cc8xn+reSq14qa9/9CIFi/GrR4XgMspQDsF3k29Zw5wQVTggPHWSCl8ndHQeASncNPW4Yset0TMRq+tMZN5Ewp1Z6KHx4dM8Kt5iNpM5EJgRaNVLq++pGb4YMIjIVWhx4edP+8mq/5frhxMOux4kG7/do+JfV2BpGwUgswdbV+cQ5uv86rCUwgHfH/TpOQ==
