apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: talks-algolia
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: job
      version: '0.0.16'
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: talks-algolia
    extraLabels:
      k8s-cleaner: 'true'
    image:
      name: vibioh/talks
      tag: '202207130948' # {"$imagepolicy": "default:flux-talks-web:tag"}
    command:
      - /revealgolia
      - -source
      - /www/doc/
      - -prefixFromFolder
    config:
      REVEALGOLIA_LOGGER_JSON: true
    secrets:
      REVEALGOLIA_APP: AgCj79yL7RY/Ykv04YeRUQEo5F7NTB3sVS6vvLvpW4nSokaWWyM3tFqrR5xLhSlhtBPCoCBZTlyXKFnZvbq0cnFZ5ZfgQPhRJEFQWjQxD3Pr5gSs28xaPV2UEEp8Ik6KhVZKaeMFlh9xlbv67jxQCwbyJ4R15W9px2HWiNAMq12I5141/LlhQXhHNaSKuiIUE32K92xu4pQMC68XmYHDd2IgGdox+IKB0tSE7t5n/AWZyB4WvU9SYtw65uZcGWgJkSUwfGl+p9UKFrfu2+gg/S8xhW6A6xRz12bZVwL14O1zdUg91m7KwofQVVeMSO2pjbrDlhZMW2pm6g9c6Qi7BgfSgecIN+2p/YdJdUoVsmnDSIu6Og19nA2CT9/W5nr0hIhjLswf/kchcbqoJqvxHkfdJFNQPtZUlUroUDGz6v7dABEVAOIN7uoaHsp2VsZVBvprLGzwk5u/qTyPofqxYbpK7nTCef1YDBSiz4P3Y071AabVpd1myPY+VHGWgGfIaLltnAerBOPAc2r7B6o5hkNjzM5ogRdJtClylpn+7DOn5UYh4s+ytE8l8/4VR6ozyIDEb30V4hI/jNSjWvd1LQePCYzab9yHmG7FMeWr9PpuljO9AI7zQDxpcf5FP+gwAo126tnmNwICwJm6dfdp5QU+pOSN2pxa+Laflf794PPAB0/8E4pu3wK+llE2YK0JrnlC18MpjL+hE+eb
      REVEALGOLIA_INDEX: AgABT/Ny39bqqWAMqUXUCROlcRAAQ7kzZAqDuYuNFXNYzjkFROlWhE6rQEMP2cxTV+kZ/0asmDTa/0zmfSlIq+hySIMOHlL+Xux8eTaIvgHokDlXt9kv6TuFJJtqQlSuGwOrj5mCAyIliZSF8IWxQU/K8SC9Ei7Oc3mCNvsa+5dgK1M2jCaMxFQe8bRWb1aJBRphMPL8lmtdxICc+IBnwkq8P8BoJK2xwIuSBU85HG5F2961cCOSS/vfRvCLaGSrLCKojowNANuGnUG1Q+yb9780fcvpGz8huKdwF7q014lQnTb1yn+pltNYMETI9JOH/kYD15wfC1ipZYqPlSHOVYMAs0zHxzu34n9A4PKyW2iUE5VlsuuS/uqfAOPX17MURItHVd5bYYDViurnak9CPFgT2bKyJgMlFX2HAdUqtMN7cyTyC5X/z6Rwpdliamz+75QdUf3P0MbbO9K6cp61OtYt9Q44RxWIPObBDWnqahrQguNx4VkMSuMdmIayX4pcwYO9OjgQcmI4YgvDlbEan4/CUXMBGdwHQFgleSUpr7TYUObIOdFR4d6rgrwjlaL3I6YzD40dt54VPaie1MsSmxoMLCsJpAzs3r8FX95zFwf9QzTpzd3Z6/+kfjyRuLF0hSIJxACKBhqMpYfk31Kr+VK5d1qI/z3OGBn2NY2GaOBIvoQwyrIxO1xW0hvvs9XxwXHhaw5Fxg==
      REVEALGOLIA_KEY: AgA6DntuEuLV+mqWfgU/DZjgrORq4UO/Cs9LhmKbaDQbD4o9+Hdw77c/UmEXLOSmgZBj1/+c7gGVJ64bRZseoIpI3snGkbCGgnmCqncmrQiigAnhZuUeTbt45LMCZdpFyQltaEk1ROd22+aMRUfI3EN9/elWF9LTOCEJYmw4Ni79pFJokWm4D93EEMfMjzRvKBpOSboF2J/PiYzMkHQHZcmLcgkDCz3OSa5BD4OHbOSbNpjSFA70E9p7yqHYsnrxA4iPFd/2qVLLsHTVkxoO70JN+qrZYUP7+ZDO81/Qa94dBXkCh1FnzMhdAfJeyGguAQbiaCGgkzp1TKrEHs4f3TCDtqOaVbyWPCulGPZysn2SIPrW0YrbJBEoxlmztHCcp/K18ZGvW7mt45lZUFxXr60xyA0ULyU+KRtYAl6DPf8ThbVv7Uy38w0ti8NYgMiOuQzcVqH/DjCt+R1vHYULuN08Ir0DsGuo6wDXqEEQSqpD7GXds+0hCK2V9IMRav8TG9RirTvZkseHcqh5DJS5HIR0Y5vzZHlAFVyuU3NKpoPDr1KKcUEFkRRJQrGpFw0qrBrsxmPHbTlf3sZmBKAShw1ZKhao2Xs6cT5acxhkQU3Te7SzLiAApPjMuLAHiHbd7U1Qxon2XVHVCji4p2/I3nj92wuH8VAK5ro3DoWhIb4T86l/rwLy95QrQV2PJdy+ExnWSckETPGfUzTAt7N44avtF2cd3k9f96y81P3e68NvRw==
