apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: talks-algolia
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: job
      version: '0.0.8'
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: talks-algolia
    image:
      name: vibioh/talks
      tag: '202202191657' # {"$imagepolicy": "default:flux-talks-web:tag"}
    command:
    - /revealgolia
    - -source
    - /www/doc/
    - -prefixFromFolder
    config:
      REVEALGOLIA_LOGGER_JSON: true
    secrets:
      REVEALGOLIA_APP: AgBxNZK+lCMnPGlE+xOdI7dXaJhmh4cAqW9gYwrxNwXxj3zIdMz3gZrK1LOgzyXnFAWO7E/HKk2db/in+yWSORsAK4UiBYYs2jZRQeO3vJg5PT09Pvjul4TIrQiT40h/i9WkaCsRE/WwADuPGCl8LpEeeIXMX4Mc20gBS/iIOFsFPr3g/Vx1hPCmZB22sIYZ7opiqHW99V0LzBi3G+vG7a2Pzoap1ihV3xqvuLo04vEN+BH6r+fvdMcmQnlof8AG0+YXaOClaUC7gQElTqVHS9f7afYWT5QrWHYTrlzLI6llz1kKeMCB9fOD2pKmEme5XBiMJAgJt76uKwRGOMxMVm3MPB5DN5e6tRA6nM8VZHUBcdRDl/39JHG4oHjjUm+lt/kxK24n+pdBo3+yyJNkqdSbO7MkYnbxc3YyMxFxyDbEuo4EU2Kp1lUB82G78sR7QGUphR9GYRwwoqV8O5E6BuotOjwbebffbwtm90iKFBu7S9HDWcEqN5rS/e4e7qFjudjq1bQS/La0vBK2aaFSw+tgTmEBide0adRpY4CofvwsMclM85geZIlZOhOCELNfKaM4fZJGifQG5hNi7C2hZSC6IR9Hc+tGx39y8Yk/v/S7HGpLAfNoMvjDYJtW90j0yXNQHpYQAEgEwOoy6LxeIBLzaXKrTqrZCMTqOKmm93qKJEh2CX+ngmqZepov6Ex/ssZC/C18e+Q8Eowj
      REVEALGOLIA_INDEX: AgCe9X1jM3tZyT/BHtlA6gy16jHHTJNZ5fa3TQJLtvuezwJLCVPnoWifoSUibJ2nQPi14kHWwJM+aDrR74SJTMQxc/25aWvV6XDypamgaUm1hfAdoYbIyoekV0zFxug76XzTAOciyeZej6IL3C01WqJtE0OW4rl/rN2RGNv1JbQo8YJ9Sym5uK60yWKosEbztKTRcGHJizfG/wC3xpiiJPxQZJq0erMXYcHfiIm8cIblwvQK+zKqBk0YxxG1wtOOCVS2g+t82EG3DqIjr+UTlWR/Pg6RHkvzptOCFw5meIywkxNnenNlDvAkJCkAqs1SyhlBTwDNOR7MWrqW9H8/kP/mYpyHCMAzL5NbIlI+3r6zDgmMUcIZ/3Pvd0HQRWPU3pUIt0spf7vd0hCBjFNxNZ/DI/gWnCaJz4Gl/sRizezchoxP1H8jlbM8y/dlXas0YCeLONrVpEzkCi/dqCGnCfAaGbdDzhdBGW1X49io2v8y1B9MHLiXNQcSsRZyogmgMwTMGhYN+EZG3gem5mkadpW9Le/ZnoJNgSIV581pZwhAXJoTvDPrm2m+B2Lrym2JwVVyIxw0TnlF/8oq2q6tsY38R0D7+Mw9ydUTZ5RAuzigqIHrzlZL1HC1UVQ/ktR4a58BMXDJtxgU2MeOSF609HV7C0/fAQRVqJQiFaeVoMPq2YTY53wQIwKW6ZZ2M2ePpDUhQ/pmuA==
      REVEALGOLIA_KEY: AgB4AOoCDedV+mhYxG3aSeH5Lpxtdavv7+l9FvuT6zhZktz43YmbhDJUzriV8jrl6XPiBvu5VfWQ3ogsgbkE6KMI1xcS4KTzsnTpgqVMG+G36nOi8guqTwnvjLg+dONnHAFvdTNnOMIpgK0x7JmC6jaqH9cneZCQQTZxBiCfGbRQc+A3myhvIgEvZSFoWTGk5nPLhs0azUN/VgkXurSKpu9CoUnz8gcSLKKruMg/gpekUKPzRYiltuUIN6EtKHuiqcmAaf3cfXcUDII24DWF+uoj8r8dvRZAGSc938dDesLlssdjCiovVRUCO1OLCXEO5Hp+txK+puAvKjFWSMlTvyCeAeoMyvk4fIbKv56mggEQpWPFXFPFtAspfFUsOIaXc82yPenonLAITaar6+dsx9cck/ySUMLC9Cq2mXAo7iBZIBR74c8UfEUMAKhxvuu12m7YBbeSKEQWVJaGhlCzaJAoOcZ1IcRGD+QrYWkaNHZ/SR/ub7KXQvJzseLkBtr/Z43ZAovwkfRLeheDX635xUhJ2Ih3kTjY8H0WNXTEF7F3l8h1njoUbEVbOm5Y7Gd6WLgHatL//mcIUeX1RzaXl4t/N+4OrArUM9CARTcCjxEk+kbKv+4kE0Qju+bsyeT0chOwEvAEskbgi9NeuSQRRiGjBLTHJsJbgFfNBsfB5h5dMReyNM2kjJKql7+i0fC65cp2+DnYDxT8N0w45s0nKbkolPU8qccRI5ksqiaSWA+egQ==
