apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: talks-algolia
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: job
      version: '0.0.16'
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: talks-algolia
    extraLabels:
      k8s-cleaner: 'true'
    image:
      name: vibioh/talks
      tag: '202208141356' # {"$imagepolicy": "default:flux-talks-web:tag"}
    command:
      - /revealgolia
      - -source
      - /www/doc/
      - -prefixFromFolder
    config:
      REVEALGOLIA_LOGGER_JSON: true
    secrets:
      REVEALGOLIA_APP: AgBZnvLNdXOlbF4TYe3Px6yuG69eW2jNDlIQNn2iScnGXyYpIY9+NwxvqGQF9VNR/SLFsw1Bcr38zChO7N4Waq9RV2Wbaa0Mwx5iCkdoFZOTXtpA5t3VwYpDuOXuytZgoFiCQZHpnt7aAFm8BNcybgkiZRlFuy97eSq3Mm4ddOyV+xxiif/BgmzCC9tu/CmmoYlYGqme51HI7yTlSvMVOshar+oMAoCaMjjM2XQxx4kgzKOAHnTko8eiokoozmQkPyKukLHFvycu2bHVZFBzxQ2/JD9NUf7zmn8GzJr1fNRXTIToNQGf/8rxOhvSNWgzQJoERDx3O4t8GzGP9Tf0Z4c6iJJI6Op+wo0qnCdM49F+qpE5+BEx1yfbLrHfK8AlwVX05ZSt5fmkJbh1jZJZgiUicfAUi4VsmBEnAgd9Ck9ux8bjnqWtf2frU6mOCbDm1ph36pn6+PTTgl2y5ykbNbjqWh+q5zG3SJ1poViBeoOPx+sRPDKKO0C1+iW83qNsYZI/HRcq9jowtGpUmAP1UBLzWmhGeroCarFKlk3HA2fzn+P/5Fr2Cq4B0bF7PbxhST72Wg0VSIeXnjx74Z6ujm6Rr1cQa3QYk915acpi5Y/XYi9Abh+ZUJhwRmvHLE31ul/k5DShronxpjTAkB5H6Fd5+Qr9ujX0lZcac7wEUOE/ocS6NvchEsxGdOQyY35f3EiBMqz0VyrvPuAf
      REVEALGOLIA_INDEX: AgBtp4zff3SX3aR9RPyOwWuxLJDK0mVcbeAwxMF9kRchirnAammv7ORs4+rI1JfdoXZcRJUuaKZY7sZ+f6Fq5Nk5IBjJMCnbZrW7ovYCvI4LNfyHmbi9y0ngiC7vuCudC6Vn6mIpzpYQQ/ga4oZ8kefFjzdpd91DLmdLSaggHCSMsh1FpI+g7WHlxiMeKHM00l0WenxhQybN0BbChSvl2rLJ/KXKiBwqv5Lnf05i+7wnuC15Ocaoy3VFkUUmht7rOpFzHHXB/pUO0aefYnTtRmeAVzgDGE6rGmLXtnJZRrNDiMY7uhFc6nS+8OLF17eRFuCppgNN1l3MICaDhM+56t4oEmyrNZZnWJuZTaE01sLmbDEnXebRfjxmZb2RL+xX/xKTaRZqbD16lthR6DKMk981RD1nJIE7N99hwQusQohCkihnt+Y4SMHZrdZcB9Mq9B0fbE3k5PjkiYMzEshcz3+rzLCkCP5TF+3n/WwAM8pruunylrvt36hGmvj6+UXh0upiQH5SojuTrXJgT5smXCu7Redl4hKuO/LAlVjcRuVukGa7iMsRnHuFqVqWlIzV0ePAufwbndjO2sd+F65sXcogwltDfoXU06HMFddWVsihKranWpAf9lZvkwuYxNnsg4SoDMoBR0OYyizTcp1YZsuwVQetb4hHbFqsBS3o2l9j9LeMFx6XVMuJUwlVzJLUVf90+ZMSaw==
      REVEALGOLIA_KEY: AgB9AhbEI0C9BI6d1067xtb7hzeJcqocYqwxYqDvt6f3SAwx6JS3r0my3b5ubL8sJMhb39tz06tX5Km+kZ0eWPPpaIAttp6JygEsCZ+5af2TI7PrsOM9mCOOZe1SKnmaqz1nptEl+thTU174sdeOyRzoy5DV2AY07+BMYGQd8jn70ZsAUweFFoc61bprYkCf2SyMRTDniX+bRV0iwwX+Uch4aXBzEe1v9V01KVMTPtmfv9X+ZftAa415W52GTLM0Yf2RuV+IrP4uO9Z1hD7xKe4cbY9TpCV56VSqLZsTk/YQVUIuuCeKvm8KoXJrkhvzCfLS13xGrb2pLHiJcMjISlh2Vgn6KTp5q3+ePwvkpD6/1Z7v+AAwG3Hz/K6Y/VMOFE5i4KAFra7cC8DriqHTdzmrDOKkL3p53ICPJsgPKgIef6J/iu+rkL979LXgp4rbTWTfNx0pB78QUK8KnSjoOWoLblXyizirM89cgZm6CaemjOtkVFdaIIU3Rr1+iJYFu4MylV+GxOUc1zOZFBsdZhYO6Y7DDmvyQIBSIuhRldaDEU1BRmTyiR7LyGTwG0fj9Dwwh7yq/8/ZhZgXFggijdPFC3flfRq9q3/cDIS313aUYL9O8d78AXnnr3vAVzxZE+Tffh4XBcjjV1hSVE/qO2GxLHOQGJTEj/v+R0m94I+onZaPfIJxgm0sbQxwCEa9O+sDD8+8ft0UnQ3ucmgTfT1Qlad2pAIvUV53YkyFzaZhDA==
