apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: talks-algolia
  namespace: default
spec:
  encryptedData:
    REVEALGOLIA_KEY: AgB9AhbEI0C9BI6d1067xtb7hzeJcqocYqwxYqDvt6f3SAwx6JS3r0my3b5ubL8sJMhb39tz06tX5Km+kZ0eWPPpaIAttp6JygEsCZ+5af2TI7PrsOM9mCOOZe1SKnmaqz1nptEl+thTU174sdeOyRzoy5DV2AY07+BMYGQd8jn70ZsAUweFFoc61bprYkCf2SyMRTDniX+bRV0iwwX+Uch4aXBzEe1v9V01KVMTPtmfv9X+ZftAa415W52GTLM0Yf2RuV+IrP4uO9Z1hD7xKe4cbY9TpCV56VSqLZsTk/YQVUIuuCeKvm8KoXJrkhvzCfLS13xGrb2pLHiJcMjISlh2Vgn6KTp5q3+ePwvkpD6/1Z7v+AAwG3Hz/K6Y/VMOFE5i4KAFra7cC8DriqHTdzmrDOKkL3p53ICPJsgPKgIef6J/iu+rkL979LXgp4rbTWTfNx0pB78QUK8KnSjoOWoLblXyizirM89cgZm6CaemjOtkVFdaIIU3Rr1+iJYFu4MylV+GxOUc1zOZFBsdZhYO6Y7DDmvyQIBSIuhRldaDEU1BRmTyiR7LyGTwG0fj9Dwwh7yq/8/ZhZgXFggijdPFC3flfRq9q3/cDIS313aUYL9O8d78AXnnr3vAVzxZE+Tffh4XBcjjV1hSVE/qO2GxLHOQGJTEj/v+R0m94I+onZaPfIJxgm0sbQxwCEa9O+sDD8+8ft0UnQ3ucmgTfT1Qlad2pAIvUV53YkyFzaZhDA==
---
apiVersion: batch/v1
kind: Job
metadata:
  name: talks-algolia
  namespace: default
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/version: latest
    k8s-cleaner: 'true'
spec:
  backoffLimit: 3
  template:
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
        - name: dockerhub
      restartPolicy: OnFailure
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: algolia
          image: vibioh/talks:202308192213 # {"$imagepolicy": "default:flux-talks-web"}
          imagePullPolicy: Always
          command:
            - /revealgolia
            - -source
            - /www/doc/
            - -prefixFromFolder
          envFrom:
            - secretRef:
                name: talks-algolia
          env:
            - name: REVEALGOLIA_LOGGER_JSON
              value: 'true'
            - name: REVEALGOLIA_APP
              valueFrom:
                secretKeyRef:
                  name: talks
                  key: ALGOLIA_APP
            - name: REVEALGOLIA_INDEX
              valueFrom:
                secretKeyRef:
                  name: talks
                  key: ALGOLIA_INDEX
          resources:
            limits:
              memory: 64Mi
            requests:
              cpu: 100m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
