apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: talks-algolia
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: job
      version: '0.0.14'
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: talks-algolia
    extraLabels:
      k8s-cleaner: 'true'
    image:
      name: vibioh/talks
      tag: '202207130948' # {"$imagepolicy": "default:flux-talks-web:tag"}
    command:
      - /revealgolia
      - -source
      - /www/doc/
      - -prefixFromFolder
    config:
      REVEALGOLIA_LOGGER_JSON: true
    secrets:
      REVEALGOLIA_APP: AgBgQcnZgbTa3+ab55Bp2qUn17AeMOxYvPg2ivJSYLtADUpjprj7ccF07WZljtfnkPfsq99ME4MFGMaNChezZfIZ5UH23QD0TmEy7PLO4SeHFep27UJ0ntOX40O6PRLgBlWCdHUG6gecRfrjWMqkN6MCRXbfJRm2zOiN2VKjVRoIT7lRh3x0YNtEQ+952Z0+nc3eqFLu4J4tFhiGVOL9CqCZaaFFuHYA45RMkm7MAIF03qhFy8vvwMtavrxbkWpmR6DOFzUkHA5ie5usNbcLmVwNNYoA3ytD6PDbGO8RswaEeVYz/oFyWYW1ZJe/wlk9BUEsw559TDQpvReN7aq3NiY+Ae5SJcWkINISMPNVlBdYI54VnWxspfOSB+XBATus/q3uFtz8yx/obLdLjMWFMu+Y5Fh6C1ApoqDjE0i9ynr5T9Iv4cXf0VoA+MkOwi9S2a4ioKl5/qTDxb0KSUZjDoLC7MRDnAjRf/gXYtfzZAzUI15N4CflXBeC/85BQkAlR9nj6q0/YxSXMbpfPNdMQrwTtpvtyOI0aTDjZbWegGeW4FrD1FFrfNtlWHNx0QF8o5TdsQwFMiGpJEPcFpoEEEWrTfcgEsIyPw/5yc+LHnNq8GqQWJVjxyoKNeA2TeDUmYByapaimgOaAqFkqwXpT5qj89UrG1d0dQ/wr2aMCTKmxOYAPnZgpOLwtWo8gVX8i6K+nEhin96hfqlv
      REVEALGOLIA_INDEX: AgCGe0c8/kux+3Nt/lEMd+tNVsSA3+5l5GkxxjVefDgG4yvd/UwfWEMKTdgoxMi8UrOCNFAvUwKFXD6zGu5DI3rr11siRuU1FinHGZcWEj+qkBEMmlZ5rt7N2HIQ5hWOSrtxSszxJ1T04YHzCxukV2YmVw8CYFx1EuIhPA3l8wcyS/dtXXCXHHDfsKUX68seCeAs1KjX33hlIvg3X8+ICvAtBPfCnReqcxNxL6h1oW186yk3CO+rctvsAtI3ivtzAa7eiVdyfi82lPtXdplmd3M+n43kCRc36oM3VhuhoLuIcqf85o1iGrpmOkV9JyVPL8ItfN+bQC33/D+8cVXUrvupar3E0vVIHNMz0tefBnWb3bmcdw7IwQOPfR7WjUiZZw3UScndcTsoqjyunNdltI8zxFgNahdsUJmPdaXiP1ApH3+n0EZlZBO4jtpKdh0gF2PCEOxBXQyGqzXPbu55nPIrYWOwBjVEsL0e0ZnE4jLpvYlhuv5M2zQH60BwHhqvPwih+P/rGxdAneMVEtNGHwbG1+p4Yq41OS4tpamiZL4viCunrdPfG3x1W6jYCHKgLHK52yKiN7c3sfX5Ph4zib5lo4atFeC84fbuciPquwi6PZIk3MFdnZcOpWbg270fdWOGlB+MjE9Pv0n6FZ/FKzqdPtO2w8hsjmA5rjJQFB7EvVyri3cd4mpWITrSfiegxvkoTGgs3Q==
      REVEALGOLIA_KEY: AgAA+Kgtn+OBXiSIdh1ysYi09bGU5xlA4RxCWyBODkYJX5hxopT4HlvVDkZcVea5KN62pECzaykX+3zbg06msa63kdR35+zNPz+XVfGjfZzZvevkqUi0iI+wXIRMTMvxJDVuQR1/p879TLFwCqZviIjim8PqbFJ1nc31igYqx9RSKhnEG9uWRzYWmu67cN+Vdq+b/eNOf6LEY1/LBi1wpSEwjgNjDTTK7wFdptuJiDaZYQtEYVkGdjTIJ5ubTwnMXiek7qrySVjRSHNvtUJJG6R5Mi78wsAY/3ZBe54+MZN4DuvFMCBy0RKFwics/b1MSooUpNLQMehWKuM2CzxHYdfmrygPeHh/H/aWlvjtV5O7T7Kjfeok/r7R7GPoaXZ2kyCdDPhkj4OYSI6RBGPKCa3Tcs+HYe1cvaK37d5QngFxO3Flts7hSuW2MRtmdrOF3J1Xvmyy1ht6nYheBJbUhd5R0EwmpfFJh0vUvQc6tnYvSMRuWHRRSV1wtqB8SGjG3DuxbZAO66Dh7KiIBPPRZwwJl5zglKgW8UdIMikSDDqlxHNRbyE8m2qxDhmxt0ce68D0y0jqRPZa2pRUFiByZPrxe/DJxr6lrqEf95b8thJfGn8FZN9yZ6EMHYSampgVUHvH04IX9BOmDMb7fiXrOlx26MD50m2quc4RiF88REmezQrkJ9vifPAW0ugchcxoDiirBKcAxF93tDPX5hfs79JacGzPuyAYf3G1pDXdDATFxA==
