---
apiVersion: v1
kind: Service
metadata:
  name: talks
  labels:
    app.kubernetes.io/name: talks
    app.kubernetes.io/instance: talks
    app.kubernetes.io/managed-by: kubectl
spec:
  selector:
    name: talks
  ports:
    - name: http
      port: 80
      targetPort: http
