apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: talks-algolia
  namespace: default
spec:
  encryptedData:
    REVEALGOLIA_KEY: AgB9AhbEI0C9BI6d1067xtb7hzeJcqocYqwxYqDvt6f3SAwx6JS3r0my3b5ubL8sJMhb39tz06tX5Km+kZ0eWPPpaIAttp6JygEsCZ+5af2TI7PrsOM9mCOOZe1SKnmaqz1nptEl+thTU174sdeOyRzoy5DV2AY07+BMYGQd8jn70ZsAUweFFoc61bprYkCf2SyMRTDniX+bRV0iwwX+Uch4aXBzEe1v9V01KVMTPtmfv9X+ZftAa415W52GTLM0Yf2RuV+IrP4uO9Z1hD7xKe4cbY9TpCV56VSqLZsTk/YQVUIuuCeKvm8KoXJrkhvzCfLS13xGrb2pLHiJcMjISlh2Vgn6KTp5q3+ePwvkpD6/1Z7v+AAwG3Hz/K6Y/VMOFE5i4KAFra7cC8DriqHTdzmrDOKkL3p53ICPJsgPKgIef6J/iu+rkL979LXgp4rbTWTfNx0pB78QUK8KnSjoOWoLblXyizirM89cgZm6CaemjOtkVFdaIIU3Rr1+iJYFu4MylV+GxOUc1zOZFBsdZhYO6Y7DDmvyQIBSIuhRldaDEU1BRmTyiR7LyGTwG0fj9Dwwh7yq/8/ZhZgXFggijdPFC3flfRq9q3/cDIS313aUYL9O8d78AXnnr3vAVzxZE+Tffh4XBcjjV1hSVE/qO2GxLHOQGJTEj/v+R0m94I+onZaPfIJxgm0sbQxwCEa9O+sDD8+8ft0UnQ3ucmgTfT1Qlad2pAIvUV53YkyFzaZhDA==
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: talks
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: '0.1.3'
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: talks
    image:
      name: vibioh/talks
      tag: '202406161329' # {"$imagepolicy": "default:flux-talks-web:tag"}
    labels:
      tags.datadoghq.com/env: 'production'
      tags.datadoghq.com/service: 'talks'
      tags.datadoghq.com/version: '202406161329' # {"$imagepolicy": "default:flux-talks-web:tag"}
    env:
      - name: GOMAXPROCS
        valueFrom:
          resourceFieldRef:
            resource: limits.cpu
      - name: GOMEMLIMIT
        valueFrom:
          resourceFieldRef:
            resource: limits.memory
      - name: VERSION
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['tags.datadoghq.com/version']
      - name: OTEL_SERVICE_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['tags.datadoghq.com/service']
    config:
      OTEL_RESOURCE_ATTRIBUTES: env=production,git.repository_url=github.com/ViBiOh/talks
      VIWS_GZIP: 'false'
      VIWS_LOGGER_JSON: 'true'
      VIWS_PPROF_AGENT: http://datadog.observability:8126
      VIWS_TELEMETRY_URL: datadog.observability:4317
    secrets:
      ALGOLIA_APP: AgCTTvzQfdmzmNhqGnsoyJZkFCRSCj9iEmnl8KJsTxUQ3Dv1FUmm9TxVhO81yBEWlKOzkeoOv5kNr8ir26hH91c7tNrxNq3seNhRHZZRe9+jcSVytfS6JOtxBgNMZjaBCGSbuqiedSG1HzhgeSvQgtCDFVuc3+AcUK4CS3r5GHhZJPahHydEW28bfBr4uIHPuM8hLJkafbhJAkfR3YztfZy0uRRMZIOFCqj0yP90h8hsQqS94zhmrUaGBIGTehftiihZ9eXMfrfDnII7ybZEaq82VaR/YijVDahK+yckpK1UK9vvCkXxIeQz5nI5t9CnfaY8xxb7DjxueLpMBNIwhtZq2QN5PRUops8kgMfkCCkxmACTH9z64Tfuz0FFvfvN77yrJWp1H2M5IgZ8Y/X7jwITKeufgv1xfcpcEoT8XQqhsdrK+cIT8oTdSRY5xfPJVa0ON75hbDtjuqlZKIQ4mFmYkA641WMK6DvSNVP1ot3nYfUnX2/bfSLc7OJOnVMgXqgpq46zpiRivnTgg9cIBBzarKIJ+l1DzSGyARf4P9JRr+FDS62I1Bg0PbJi+j3oAax9y26o2XQEOcuVXAFz7rR/xuSzM/H+gsPCqCyCgI2vdIr266cEzjPtMzJ+563oXkqyrCdoE3eXtb8SsiRVHaoIJfm+6PxyfOaaaw8bHrGVVvuiKFWGyuweao5UchA51SB301Y+Os0BRymC
      ALGOLIA_INDEX: AgBVbMVpsfrjAQCSLrnxKxLSBkjKfvcETWvcc4RCEk1+7uZj48dL1j820syK1WyO3apiLZfB6VVjSjqfa3vmsslMtm+H4nf4cqlj/lCd0nHltoUeplz5unBNf/SA7J1w1N1R0pOZ5BBxaMXXHw5l/j5qkIjOkyluqOuQe8klLynMxgMBn9ZYYtJQ7C9Gb2xxM1sskeqfhGpzhJEckLpXIvXHojwjRiDlrqFzmMREe5ls25ITLSUAOCsvJ+6KVM4CwPr6muzJx4ky/N43rm8qCAhkkA8Gp6xoCBm9nviZInX4js0N7weZeTAy9VSEjWV+jB2k5oss0Vk0B6/huvYgA4i0WhMwFASwRqQoGH9s1D+CF/8+D14a714pzvKQ3B51hV5mpk4rueualOP2mjPq58KZu3PKv0jmAw3HYp7smvvFszogmC5pFGQn8uCw2mb9rDwy+JRy9YD1I7TtBWKTpgFCE3FoDlzCsHvudErSACEtKkCSIcbfQyb01IObxiK1LtDjVWdOR2vSZHA4OhUdi08lWCukSehGqutWRiPtJjDV/wb2DelBPK4axijC0TtngHqH8grD/8m8lcGA0ltKbowkeYdVep42qR1e7GWAzK5P47ngDwNDw+uK/JlHZfkS7/FIV4P7tI15G9ccuYqprKSuzv0Rbi3R4bHcqXpFajPYuIRJ4LGe+Vh9q8eV9ChfuFMRHLRyKw==
      ALGOLIA_KEY: AgBV0nJcWmpw105VCY6VppwrHBmvswytX76CwJLO6kygdIAC6knKNvUQF7kkugx1MWgSmcHJRKdkqUUZTJNIyef3uuikKQRHpZDJOv6LuHB+a+027WjYqlhvZEDd9yd+s+vaX/JmtDGGyIC0yb/RZF6ldY3SHamGbRWiJbpELYCstN0JOmdufRWujNVhSpC0/CL51/wPcFyEYfxe4Vhk2InWGC5qGsDJfL/eUTQMc6x3DxYM4IHahvL/ntP7N5dedNFdr1oo6KLGupBTpzAYY8RYFlG34CSFzglQNRujJVHNiXM0l2zP9CQD0Q6bAMKUY2RwAd9DamjLvxtx12Za4rNCzUHOMUroNyH0FN5+mTQEQJ+GKguxXpmen6IRIcpTyLPR3EM4gXBC7XImNclxGbqJZTMAXRChZgkX9FTBOU4wH7mbV55kz/Ry7IMydVB52IdRSRByct38Wh4zRvwl5biTiYHGx5mlUpcRhVuqgOeQZdgfmBgDkG4eXmVMIbuwIEDnGDRT6mEV4EGaYCzY9ekfzci7DDLk9XASqgFsd1GeIlFzsnQwfio8oQbebyxd1Yljee/uvo3dq5RP7l6nDUNVSWrlj2MJsfTGDLgyWtcKPOURcAcosmHS1pTRH0SDsUSIWhsJtRnRn9oaNiKrRgoO05xP5OuRQopT4gGzFRznAbhgOsEEV5QEkxWl9K8oXGOsQenwqtTCJpLZomHFTz+RgzFvGyNKb6Jgr6pfplKQqg==
    autoscaling:
      enabled: false
    initContainers:
      - name: algolia
        image: vibioh/talks:202406161329 # {"$imagepolicy": "default:flux-talks-web"}
        imagePullPolicy: Always
        command:
          - /revealgolia
          - -source
          - /www/doc/
          - -prefixFromFolder
        envFrom:
          - secretRef:
              name: talks-algolia
        env:
          - name: REVEALGOLIA_LOGGER_JSON
            value: 'true'
          - name: REVEALGOLIA_APP
            valueFrom:
              secretKeyRef:
                name: talks
                key: ALGOLIA_APP
          - name: REVEALGOLIA_INDEX
            valueFrom:
              secretKeyRef:
                name: talks
                key: ALGOLIA_INDEX
        resources:
          limits:
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
