apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: talks
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: '0.0.80'
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: talks
    image:
      name: vibioh/talks
      tag: '202201300755' # {"$imagepolicy": "default:flux-talks-web:tag"}
    config:
      VIWS_LOGGER_JSON: 'true'
      VIWS_PROMETHEUS_GZIP: 'false'
      VIWS_GZIP: 'false'
    secrets:
      ALGOLIA_APP: AgCKYWr1Se2PsjfRaIT7vdpqCgdpyzsXKAE019l61G6k2WOyVz7Q5CtnWe5oBx7Xu9xrse6BaJD3K2ieIQ5ioqpQuNOJ8flahrKphElIxZvHsa9nm0MvFUj+JtxTN4L9WowqgbgeWlf2qkPr2u36s1dFdRW9yIAHdLk9KQtq7SPXqiloeEhE3Fzp58dcWEJhpgxVZeX6UdctZg/73CDvYc+iZEjb1rSQBc5/I45NgkQua/Z0hv5SYD1zV7+od5u11/tQt4vf/VbjWkb6JDC4evlbThIRhGi2QsRIpfWBTucqqROCSpftejSElH/DGi6gc9P6X9bsxcFCIiVD1VbQ3H/eTsKjBbFktT3wdGLx99ts4l+vkA/y8UpAVhSUaSrSmsTXdBXqRZH24jE6LDS7F+RqxO9mV3bvnrpY9k/KST8ek4Mc6kGDvskoQEBCmwhTqBGXFAtqlyR6kRzXbfT3+GauqVK6WE6RHavmo7UH2vSs4+3/WaWfG+83atrY8Y7gpMgpZMCL3yh8awPAuEc2TJP4QZcgAf4j5FFgv4NGQY9vAIxAJSWG2EjYxPdrkIXpKTo0OC47th0w5iwtd3CqmsGKA4LEoYNlTgaeOWQqPdIqAv4gUtNKyGIKzXfBlAw3OWBcVlY935YAwTE/a3GIMWZLqb++yl55uiYAEn8jQDQycRpRjnpo3/CayF77DsOhwIC6NDm+W38RliRS
      ALGOLIA_INDEX: AgAIy2/lIvRPFRNg3+Lcj9ynUltxtWYwSVwcRavh2+5sGIvc0Nx0xZSJ7fCgZsnoeEz9i33ljLETcgPBtGaS25nTzrZXbfQ2WuWmUb7/7vNyMdaEpoXOqUSEwspGz0a+PuqwJBdrZ/qVMfuZ/sssriaXgLUTHc018KbU7aHsNsuMzmyniub2scmO7Zxbkh9CTMpGGYd1+qtE3x7hcWIm/AUZLlAI3QzWjMTPf0i4CPC1vG0qgmrg8cLaJUu34MAioYUME89j5aSGcyy05NyqvdbUP5m+bwtFp0nsFm0GNHiBAgygAMpBOOIQnH+ClRvHv+meN2Ma4nP92LykxBQkP1QefGILRyq5LMzw7rLNdX+bB52beGrym2rQc9R6VnPmjDqOfvaq4jwlUVdZXMxIF+mKnDWf0k6n9uo/DCMyGHKFJDSBhuhml8lCTPHEY43boOqfTfcvb0LHkPvRVqzxTz1cBlbHZaU0+8Ak0FyH3ppuS7Tye2l4A0BdziqU6CeWyRJdOkiqUia7V+GDPQCaZtNSLQdLi18JHX5Sx6h9Zqg62q+JO1zeUWb0fUq2oHLKoH/RFkKXJLBSO6cHPiHQtdtNsxqmtNLxSN56qqd8FDrxir8EmGj6TBjL18VyV+XxtK11Bz5ud7QXpIyj3xChdKEk4OCdWrg8Ynv8tj6mXCZEEtC773jpUZmYsb0JRCMdTQSdml/4mw==
      ALGOLIA_KEY: AgC30wdLkkbK35reZupvbnA+sFWsA9JG3PpW8g8ryrjnmMW8Gi69BNZ+elimzHXHqc5cQOgJIITWVACBDQunQW6uUF4OQ8y5uTAKD9kT7EKfkkyweZkKP0PeK1sH+Q9cEJk+o47+QmFegR6gnU3Lij6TrwxmAyRPSDbLvQcFYMmcdCHrQTevW6mEwH4ZXk90o4FJsAghsfYEeO+98VDNPhGhU+8TYlf1e+e8jlgIe5K1Dcx5Ysar3HuVzDmOBheurdPgSu3TNKXdj4i0cDK1xWn6Q6Puf9sXXfq1iTKhwe+KDO4xZjkClm7TRXF3stO3i5u7NJbpNvqFv2/kDREweiOM4+T8emOilQtqB7H5xn+1byZuThLhGvLHqTebxVYVEzk84v0vtBJwaUCBcBcsohtrxKiUgJPBt2JCyllMgwf8m8m0ywHzjol47z+2nP51b/mCvzb+BUGP1JbRUhMsxZ0DpZpMscLJNQS/Mz/LgAsDQOIjXfX4elLC83M/cgevln/pngc2FztARMMmBqG3QH/VFKDaVgeW5l2cA7DSBMWaD+N/cjukc/AFiRJRviWs9ZPd9R8VMkS4iz2ZJi/sqGl9P/Ae5SdFRUO2eoLXwdsFZBCXax/rw7Qg+fp6Lc1kefn+7shViK9XT3AFzS1tzbGnJiyPG5dVCed8jLA/GTWWw+WCMaEV+SOc8nKimTq1Cy73C7AH9sA+qHE4rzRhAZlNblX/vB+p6lwexufSFEJbGg==
    ingress:
      enabled: true
      hosts:
        - talks.vibioh.fr
    canary:
      enabled: true
      url: https://talks.vibioh.fr
