apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: talks
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: '0.0.81'
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: talks
    image:
      name: vibioh/talks
      tag: '202206251550' # {"$imagepolicy": "default:flux-talks-web:tag"}
    config:
      VIWS_LOGGER_JSON: 'true'
      VIWS_PROMETHEUS_GZIP: 'false'
      VIWS_GZIP: 'false'
    secrets:
      ALGOLIA_APP: AgBunaeTZgVAfC7XHjOKomYOEeY8Uwa5iTA0bMj8oUxVBWZfnzHUbU2z4GN0ym7TQHrpxOokPRsLxmSy3m2lQAGP6hlTa7+N1jXfLG6ua6NaWj/CaSCDiHJ7pFZMYeUpxPolCvi0iiN0DNMSXa9j7wA1/AFocDXMY4DjdFHu/kOEIq1DI9MpsUW2H99JPZSYuBwymkMOiGiYmTb8JIjEyk22pvhdfKbWCldbAqTeNLKPyoZnjSRcyGbwj5hyGda1rZz+ovJ39tByu+ypIHKizNiyOux6hGU4y61RNP18pTHEl+/qLMk1UKvW/Wn3Eg4CWU2c0eJuO41Ua+XjAC0siXY0HecW2eOUs5DaTjP3Xioz/cK+h0uemHSWxvNyzXW81N/Wa6B3WUwFBWwOQOogas4nYirnYnxtUqPd2lsb7bAYqZyka99OmXJNU0mlxGBu1J1kQb1IlRDl8v3Y+YiaCxA1dvdq0qCRvCiy/S7s3MWHrCreOoTJ8REa1bUrP7LMLG66Nng6H5AQWpwVMZE/J/2Fj9VXEXpdMQyXJhiVMU5JH4/V5e3fSj8QLX5ZVxeyY+Ljj6nMOJScMyEg2m47D4VIbqbQYwa7eSedU/Z35vzieXHUyz2X2W0DYWVWaUvLL5Kn2m5uD4TS/MTjhHAqiPhKBOuPK60Xf7Apzovjw+JidAV5fCh/AwPW7cN/aIeMUk/q7RdRKAhMvQH3
      ALGOLIA_INDEX: AgCtIhHoNrqA/gr9W9WLcZZUV3Gr/C2sOIl61fz6lSoIUzXNY8jWHo5mrRPVz83eJnPZojiaNJ1yiDOVxUucTpuiJeHRQ9R+LJlmLN4q4eY9MmO1CwTUbPCl20goaztnCPZBiKZZVEphuddVYop39PQq7p7ULaJogWV8cCHB4rlo1wmeYPv8HdPfRHnVvJ+KzhlwO1kGpTg9j+Qxhb/OmpswXabkbwHWop1Se6LJ4M5KTTIAp5TLXBVOu5rUjwHIDQR9U4sVqf54GKfFDuvkTwF9HPmhweRGbXk686dK6HvX7N3nJjlxRzTk5fh+Vuan7FDYuFG+7mcTKhfkOd6G54yXe0dJ+/pDzXc6XJejahoHdZsmflbZRUexwqo1ULQRqxhP5GxNdI6PCelCOdKgV4bc4v1c5WQf5sVtPE2Al1fMVjfuFhP61AnlW7sOWyApQhagKy9Rkl9eDRbGTNHY4KuDzl52u5zgcgqVdwLx+kCeqQY02FksBbK5rH/CP5Q7NSEyOHaQEBJzPdzRdaY9RGywmB2cscM5/ooILdb90ud1ecx9F7GSM2P+nyDO46rtKc+Ifg5wEd4o7ZHXIC4Ra8L2+W0Ex45nNAFR3O8SNT7l6u4tgMpK95V5s38g8QTrpzvHaJAIUT40LJcCFrSc6D1aJilWdhCrYrpTEJJNpjYm7WVQdcPMkzLgNgKcWhtXDvTMdj/mWg==
      ALGOLIA_KEY: AgCMiFC32ERZiUwEsbXXfr1tSw9B2vmTzFUyjMsEtPhxVFfxYfC60PH/Lqvz5NpO2SNav59tX3LzSvV20mVdGaTVN+tcOQiC5KqD6PFEFgGP+NMwS3Pn5VXuugW26QTlZDJC0BhiAJBUfG4c82UzFr2dO1+IY+MeWBX/nXE9SFwNkTHXgQkYcBNJQJgkQGPhylHxDkKEseaGwjadegYp6mpS4Smiul0fjZZKSiaOIGV8Bcrt9jtZdHwfvGcCIT8fnk1XLUrIHbtmV1XdUQg7+92xCirXm3xgYT/bbay7x3zE0NvUwUNPXGu3p8JgLRE/347DKh900+AB1V8vUr9OysUtsDJQhExMhmMJM5OAPse3/WrwPC7iMwpokXy1QN0uDoRnzaFBkzZtwvEfE6pD6s//mDaAYyAuItqxEKDD6mjz3glt+aFtHSs+V61hTwM4nMnjQGPLcp30bOsLISIKnXZE0sb+2AwA1ePHy/FsO9Fdn4/ztHRFm2zeKnVCiAAotXWzrc9/i0ly5z+8Szw9DeM4l0rH+HMEs9ajoUeLxODo5EH4BCl6dH74Jdo18zU75Ox5Tf4G97qFrhXI+qgZd9k4ZYhxJfzO74riw0DVxDpLF/P1Zx1NtiMkHtBuAHvnpNL3S5o0GlxmGFOitsqBSmv2ZlFw31M1dU2HYHv/RqH63zLJ8xHKY/PBwPZUVsMKR2smjkO5U0t4bSJROn/eemyW7l1M1ysX5m9lxIj6OGT0Jw==
    ingress:
      enabled: true
      hosts:
        - talks.vibioh.fr
    canary:
      enabled: true
      url: https://talks.vibioh.fr
    pprof:
      enabled: true
