apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: talks
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: '0.0.84'
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: talks
    image:
      name: vibioh/talks
      tag: '202207130948' # {"$imagepolicy": "default:flux-talks-web:tag"}
    config:
      VIWS_LOGGER_JSON: 'true'
      VIWS_PROMETHEUS_GZIP: 'false'
      VIWS_GZIP: 'false'
    secrets:
      ALGOLIA_APP: AgAhJzSUempmy853s6Ur+Wv6kNzQXwFH5yKJt/JGCwLNwPho5Vcf2NKuyZT5KWgGxMFQpWRLmDZtQo4pafs6gYY1FubhPQbmSZK4eluBxg6Z68AP+ffRab7NYombqvDo5Mv0u/2+6hKjN5n2o7R5uf2frLDKnya8HdDUKTFaqiUk9kBGsTANv5OqT7kGZZflvslvTmvc4JapadPMr3PLnvVKfMWxhIJ2y632IANkAnCsJ5KiEKwsTX/NBgdkPQm6pBod8mUarTfY0VbaoxYoWEg6DJV0WLwxQwrUen6B/7LF8SilTrCki9Y/8ujm6Az3Hydl7yyH4qr0pC4w93nid7d32A74gH9evjJiH/S6kmWfcjRRcjScu7TdZ1ch5mMXvZd0+1dKKlr4GYIeFcgz/8qPZcBezRlUp4JhwPLT2qJtOI9vdfe4Qd62y5DGCnLnF7VZRjY3Rcgy91LevCdx70Ee22bMs1aVYw2JOtiqcpZRadc0bq7EAhnUIuR5C0KOVnup2aW+exzp6quhU/pxwuBw+fF3sYCmGqvGvTQCXeCCI2zFeMN3ZXzU/FpWScUAB6XlTzS7IVPF0Qihq4dwS4dVfJyxagLS79IJbSa2qHxtfZRY6rsVq4VJpFKgh6/JfJM5uf5P3jMidwcgBTIlb1HL+nteL34WhC17/79QD1pdlsGn5LzYWgi9e8LZVYCoE+yCi4n+AfiLSzUO
      ALGOLIA_INDEX: AgBS26V3lP/uOQ162MIqOn1xbSJRGOg5Y5B9+39GStFprDRryA7NxS4rHD0aFIbLrrz1VeqXetRy/tY4PDP29Dac4wN9MqeweG0EtWzKn6aoeRnrM4Yj45gAEm8ZO8GspW1QJFlqZcoPZETzWJHCDIl27khxOBURulilnRjgJH8nBapVDDYWxng/jAxhtjM3PibF6Qd0reYPf2swJN2xiIXJeZNdAYfUpWzh4hiwZMG/JQcHcHYbtTXsE/G4VbFv9M2WZiFo9H1CojBr8jeaS62Ili7He4N88i49h4rLy9KMXkVFDXB7mN4YAevfpmuRpAxYnStdaGISVj/JqqiWHgJrtqx7Fn+2tFR1kFVHeyl/1s3kFjrSvvWr4p5juZxnlTC3+8uidrrO6cY++wcBmXUzNKENpn47Xp0MbwO9jlBGurHM+zN8jNdubG9oNfm/XAcyxGsqhyl9jRN7hmRM/BSlZUANo29YYnH0pFmu4aqrD6zugljyPUjEeDG5tr0zxl86CQ+AfXxrzM2c+ljksQm9SsPg/xbZeL0NLoICajgXWpqwxxmjUh2B5/alCfr/9ebSEKt9eqp2RdgKASHUESVWFfZOnUufcOe3Qgo5MFo6M8P5k4L5gCv2/x5Fvq4wa1SFfdcrvu2DK8fhBl0aJZNbuBJ5vqrJ64nxXIQ9WCvL7UlKur5Pjjs2hQLJ9LF4RWAmaoHUSg==
      ALGOLIA_KEY: AgCD4TZvuKStxmw/X7H7w6nMrLL8jY46slRXtgY8vUnaxaU6d1WOPBwj5241HV/jXfZJrdKjOfqS8UPMbrPF6LKWBJwJ5Rf4E9kcPGW9r2CWE4hd0LT3xIvX1fFB+A9QU690m31T9Us9OZOPxlz3J0jEX7zyZOz60s+hOJPdr9rgnd/3ezs2R++v8LxDcdAZ8cw71UxUKp6ebAstLqTXZQw4EZ7BA1ItBbr6MUUbrxbHr6Ho9xbSmVT/ybeioYfyCkmGyf8dc9RD8FTMdwAWRVRVlLwtg2aeymbcom5N2NFdnj3e9pXyMOQ/TXCyhtwVDSjeuw0rWl+VzSLEpVKb2ZmtsmoTd7+poglvNlJV5dBCDzCpmduMdrwlAJGM96661p/LxAR/GnCw/6XZ+EzuLYxlyF9h5o0aWQRyC5Tkb5m/JjZVlZ1HzYkmmPKAZOWmgl9mH5OI7Zgf7yKnjtYEDm5cttIaNOSaCO0KeI18D8DW1QJN7/aqyoiLQDUkQ0uWNJKg/dMvqyXkCcZu6/PcUslBa2VJzPptwMnNTGjqXhW2vHbuMp5CJ6Ei1vOtn7SxWC/swbpjSIgzoo24aH6FM9Q4TX3u0M2eOxWNkESW9uSMlmEWaUYN1fpavxs2RfWo/MdRg8SzDmeDC6SC6owV5WEbryLIacKpjsGFg0vCWrlQEUwM0tR+4ZjunyvnUq8ZnGwdKwqPfqlYTO4UNHhzxzZp2y9+zbQ/+p1kyBwyRXNBtg==
    ingress:
      enabled: true
      hosts:
        - talks.vibioh.fr
    pprof:
      enabled: true
