---
name: Build

permissions:
  actions: none
  checks: none
  contents: read
  deployments: none
  issues: none
  packages: none
  pages: none
  pull-requests: none
  repository-projects: none
  security-events: none

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  SCRIPTS_NO_INTERACTIVE: 'true'

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Build
        run: |
          npm ci
          npm run reveal
          npm run build
          git --no-pager diff -- ':(exclude)www/js' ':(exclude)www/css' && git diff --quiet -- ':(exclude)www/js' ':(exclude)www/css'
          sed -i -e "s|{{version}}|$(make version)|g" www/index.html
          sed -i -e "s|{{version}}|$(make version)|g" www/js/index.js
